# Generated by Django 5.1.5 on 2025-02-15 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0002_crud_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crud',
            name='password',
        ),
    ]
