# Generated by Django 5.1.5 on 2025-02-17 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0003_remove_crud_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crud',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
