# Generated by Django 5.1.5 on 2025-02-17 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0004_alter_crud_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crud',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
