# Generated by Django 5.1.5 on 2025-02-19 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0005_alter_crud_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breakfast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakfastfood', models.CharField(max_length=25)),
                ('breakfastcalories', models.IntegerField()),
                ('breakfastprotein', models.FloatField()),
                ('breakfastcarbohydrate', models.FloatField()),
                ('breakfastfat', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='caloriestarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emailid', models.CharField(max_length=25)),
                ('Age', models.IntegerField()),
                ('Weight', models.IntegerField()),
                ('Height', models.IntegerField()),
                ('Target', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Dinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dinnerfood', models.CharField(max_length=25)),
                ('dinnercalories', models.IntegerField()),
                ('dinnerprotein', models.FloatField()),
                ('dinnercarbohydrate', models.FloatField()),
                ('dinnerfat', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Lunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lunchfood', models.CharField(max_length=25)),
                ('lunchcalories', models.IntegerField()),
                ('lunchprotein', models.FloatField()),
                ('lunchcarbohydrate', models.FloatField()),
                ('lunchfat', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Regist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dEmailId', models.EmailField(max_length=254)),
                ('dbasePassword', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='totalcalories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emailid', models.CharField(max_length=25)),
                ('date', models.DateField()),
                ('eatenfoods', models.CharField(max_length=25)),
                ('totalcalories', models.IntegerField()),
                ('totalprotein', models.IntegerField()),
                ('totalcarbohydrate', models.IntegerField()),
                ('totalfat', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='crud',
        ),
    ]
