name: Django CI Pipeline

on:
  push:
    branches:
      - main   # Trigger the pipeline when changes are pushed to the 'main' branch

jobs:
  test:
    runs-on: ubuntu-latest  # Run on the latest Ubuntu environment

    services:
      postgres:
        image: postgres:12
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test_db
        options: --health-cmd "pg_isready -U postgres" --health-interval 30s --health-timeout 30s --health-retries 3

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Check out the code to the GitHub runner

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Set up Python 3.8 environment

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install dependencies from requirements.txt

    - name: Set up the database
      run: |
        python manage.py migrate  # Run migrations to set up the database

    - name: Run tests
      run: |
        python manage.py test  # Run the Django tests
